In [50]:
import numpy as np
import pandas as pd
# for k in range(0,24):
#     print(f'|Day {k+1:2.0f}|&#9744;|&#9744;|') 


# Load input
filename = 'inputs\\day1.txt'
# filename = 'inputs\\day1test.txt'
curIn = np.loadtxt(filename)

# # Start by loading the data
# inputFile = open(filename)
# inputs = []
# inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [58]:
# Part 1
x = curIn
sol1 = (np.sign(x[1:] - x[:-1]) >= 0).sum()

print(f'Part 1 solution: {sol1}')

Part 1 solution: 1581


In [59]:
# Part 2
sli = x[:-2] + x[1:-1] + x[2:]
sol2 = (np.sign(sli[1:]-sli[:-1]) > 0).sum()

print(f'Part 2 solution: {sol2}')

Part 2 solution: 1618


In [55]:
print(x[:10])
print(sli[:10])

[176. 184. 188. 142. 151. 156. 157. 167. 166. 178.]
[548. 514. 481. 449. 464. 480. 490. 511. 526. 551.]


In [56]:
print(x)
print(sli)
print(sli[1:]-sli[:-1])

[ 176.  184.  188. ... 8317. 8320. 8341.]
[  548.   514.   481. ... 24922. 24943. 24978.]
[-34. -33. -32. ...  13.  21.  35.]
